all:
	#g++ -g -std=c++98 -o Test test.cpp ../ProQuickTrans/ProQuickTransAPI.cpp ../TaskPool/TaskPoolAPI.cpp -I ../TaskPool/  -I ../ProQuickTrans/ -I ./ -I ../include -lpthread -ldl
	g++ -g -std=c++98 -o Test *.cpp ../ProQuickTrans/ProQuickTransAPI.cpp ../TaskPool/TaskPoolAPI.cpp -I ../TaskPool/  -I ../ProQuickTrans/ -I ./ -I ../include -lpthread -ldl
	#arm-ca9-linux-gnueabihf-g++ -O3 -std=c++98 -o Test test.cpp ../ProQuickTrans/ProQuickTransAPI.cpp ../TaskPool/TaskPoolAPI.cpp -I ../TaskPool/  -I ../ProQuickTrans/ -I ./ -I ../include -lpthread -ldl
